#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

npx lint-staged --allow-empty

branch="$(git rev-parse --abbrev-ref HEAD)"

if [ "$branch" = "main" ]; then
    echo "You can't commit directly to main branch"
    exit 1
fi
if [ "$branch" = "staging" ]; then
    echo "You can't commit directly to staging branch"
    exit 1
fi
